### ISSUE TITLE
Suggestion: converting local packages to pypi objects

### ISSUE THREAD

**Issue by asterized** [letsbuilda/letsbuilda-pypi#3]
There could be a function that would take the output from `pip list` and create an object wrapper

**Comment by shenanigansd** [comment]
What information would you want to be provided?
Are you picturing something like [`pkgutil.iter_modules`](https://docs.python.org/3/library/pkgutil.html#pkgutil.iter_modules)?

**Comment by asterized** [comment]
Oh, didn't know that existed :p

**Comment by shenanigansd** [comment]
Yep!
